// <auto-generated />
using System;
using ElasticSearch.API.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ElasticSearch.API.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210328233916_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ElasticSearch.API.Domain.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_entities");

                    b.ToTable("entities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2021, 3, 28, 23, 39, 15, 700, DateTimeKind.Utc).AddTicks(2986),
                            Description = "Атомобиль марки Honda. Два хозяина. Состояние хорошее.",
                            Name = "Автомобиль"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2021, 3, 28, 23, 39, 15, 700, DateTimeKind.Utc).AddTicks(3333),
                            Description = "Наручные часы фирмы Rolex.",
                            Name = "Наручные часы"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2021, 3, 28, 23, 39, 15, 700, DateTimeKind.Utc).AddTicks(3342),
                            Description = "Жидкость для снятия лака. Объем 0.7 мл.",
                            Name = "Жидкоть для снятия лака"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2021, 3, 28, 23, 39, 15, 700, DateTimeKind.Utc).AddTicks(3343),
                            Description = "Щетка двухсторонняя для чистки от снега и наледи",
                            Name = "Щетка для атомобиля"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2021, 3, 28, 23, 39, 15, 700, DateTimeKind.Utc).AddTicks(3345),
                            Description = "Лак бесцветный. Объем 0.2 мл.",
                            Name = "Лак бесцветны"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2021, 3, 28, 23, 39, 15, 700, DateTimeKind.Utc).AddTicks(3348),
                            Description = "Часы наручные с электронным циферблатом.",
                            Name = "Электронные наручные часы"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2021, 3, 28, 23, 39, 15, 700, DateTimeKind.Utc).AddTicks(3350),
                            Description = "Кожанный ремешок для наручных часов",
                            Name = "Ремешок для часов"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
